# Generated by Django 4.1.3 on 2023-01-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
