# Generated by Django 4.1.3 on 2023-02-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
