# Generated by Django 4.1.3 on 2023-04-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_resetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
