# Generated by Django 4.1.3 on 2023-04-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_resetpassword_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetpassword',
            old_name='created_at',
            new_name='reset_date',
        ),
        migrations.RemoveField(
            model_name='resetpassword',
            name='code',
        ),
    ]
