# Generated by Django 4.1.3 on 2023-04-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_forgotpassword_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
