# Generated by Django 4.1.3 on 2022-12-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.IntegerField()),
                ('table_number', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
