# Generated by Django 4.1.3 on 2023-05-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='booking_duration',
            new_name='booking_time',
        ),
    ]
