# Generated by Django 4.1.3 on 2022-12-24 06:12

import booking.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.IntegerField(unique=True, validators=[booking.models.validate_phone_number])),
                ('table_capacity', models.IntegerField(default=1, validators=[booking.models.validate_table_capacity])),
                ('booking_start', models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 24, 6, 12, 42, 843740, tzinfo=datetime.timezone.utc), null=True, validators=[booking.models.validate_date])),
                ('booking_duration', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
