# Generated by Django 4.1.3 on 2023-03-15 09:53

import booking.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_customer_booking_date_remove_customer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='booking_start',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 15, 9, 53, 39, 135925, tzinfo=datetime.timezone.utc), null=True, validators=[booking.models.validate_date]),
        ),
    ]
