# Generated by Django 4.1.3 on 2023-05-14 16:12

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(validators=[booking.models.validate_phone_number]),
        ),
    ]
