# Generated by Django 4.1.3 on 2023-03-15 09:59

import booking.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_customer_booking_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='booking_start',
        ),
        migrations.AddField(
            model_name='customer',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 15, 9, 59, 13, 431112, tzinfo=datetime.timezone.utc), null=True, validators=[booking.models.validate_date]),
        ),
    ]
