# Generated by Django 4.1.3 on 2023-03-15 10:02

import booking.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_customer_booking_start_customer_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 15, 10, 2, 30, 428049, tzinfo=datetime.timezone.utc), null=True, validators=[booking.models.validate_date]),
        ),
    ]
