# Generated by Django 4.1.3 on 2023-04-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_number', models.IntegerField(primary_key=True, serialize=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
            ],
            options={
                'verbose_name_plural': 'Tables',
            },
        ),
    ]
