# Generated by Django 4.1.3 on 2022-12-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetails',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images'),
        ),
    ]
