# Generated by Django 4.1.3 on 2023-04-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddetails',
            old_name='id',
            new_name='food_id',
        ),
    ]
