# Generated by Django 4.1.3 on 2023-03-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_fooddetails_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetails',
            name='food_available',
            field=models.BooleanField(default=True),
        ),
    ]
