# Generated by Django 4.1.3 on 2023-04-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='food',
            new_name='food_id',
        ),
    ]
