# Generated by Django 4.1.3 on 2023-04-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_food_ordereditem_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
