# Generated by Django 4.1.3 on 2023-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_amount_order_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
