# Generated by Django 4.1.3 on 2023-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_table_no_order_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
